name: Continuous Integration

on:
  push:
    branches:
      - main
      - scratch
  pull_request:

jobs:
  conflux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CONFLUX_REPO }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CONFLUX_REPO }}
          aws-region: us-west-2
      - name: Download external data
        run: aws s3 cp s3://conflux-public-data-staging/openslide/external.tar.gz external.tar.gz
      - name: Build wasm library
        run: |
            rm -rf dist
            mkdir dist
            tar -xvzf external.tar.gz
            docker build -t wasm-build .
            docker run -it -v dist:/dist wasm-build /bin/bash ./build.sh
      - name: Check build success
        run: |
            if [ ! -f dist/api.wasm ]; then exit -1 fi
            if [ ! -f dist/api.js ]; then exit -1 fi